name: Build Robot Code

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ ready_for_review, synchronize, opened, reopened ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Only run on push to main or on a non-draft PR
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false)

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Setup Gradle # Caches dependencies for faster builds
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build